tic
mcc -m ccsim_for_exe.m ccsim_for_exe.fig ccsim_editor.m ccsim_editor.fig videofigWC.m user_string.m...
    print2eps.m print2array.m pdftops.m pdf2eps.m isolate_axes.m inputdlgWC.m ghostscript.m...
    fix_lines.m export_fig.m eps2pdf.m dxf2coord_ccsim.m copyfig.m brewermap_view.m brewermap.m
toc